version: '2.0'

services:

  #OPTIONAL: Uncomment the following to enable a Cloudflare Tunnel to access from anywhere
  # cloudflared:
  #   image: erisamoe/cloudflared
  #   command: tunnel --no-autoupdate run
  #   environment:
  #     - TUNNEL_TOKEN=
  #   restart: always
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

  guacd:
    container_name: guacd_compose
    image: guacamole/guacd
    networks:
      guacnetwork_compose:
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    container_name: postgres_guacamole_compose
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    image: postgres:15.2-alpine
    networks:
      guacnetwork_compose:
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d:z
    - ./data:/var/lib/postgresql/data:Z
    extra_hosts:
      - "host.docker.internal:host-gateway"

  guacamole:
    container_name: guacamole_compose
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    links:
    - guacd
    networks:
      guacnetwork_compose:
    ports:
      - 8088:8080/tcp
    restart: always
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  guacnetwork_compose:
    driver: bridge
